[package]
name = "script_merge_rename"
version = "0.1.0"
edition = "2021"

[dependencies]
gix = { version = "0.68.0" }
regex = { version = "1.11.1" }
chrono = { version = "0.4.38" }
anyhow = { version = "1.0.93" }

[dev-dependencies]
git2 = { version = "0.19.0" }
tempdir = { version = "0.3.7" }
